System.config({
  defaultJSExtensions: true,
  transpiler: "babel",
  babelOptions: {
    "ignore": [
      "github:*",
      "npm:*"
    ],
    "stage": 0,
    "optional": []
  },
  paths: {
    "github:*": "https://cdn.rawgit.com/aurelia-ui-toolkits/aurelia-kendoui-bundles/1.2.1/jspm_packages/github/*",
    "npm:*": "https://cdn.rawgit.com/aurelia-ui-toolkits/aurelia-kendoui-bundles/1.2.1/jspm_packages/npm/*",
    "bundles/bundle.js": "https://cdn.rawgit.com/aurelia-ui-toolkits/aurelia-kendoui-bundles/1.2.1/bundles/bundle.js"
  },
  map: {
    "aurelia-after-attached-plugin": "github:aurelia-ui-toolkits/aurelia-after-attached-plugin@0.1.3",
    "aurelia-animator-css": "npm:aurelia-animator-css@1.0.1",
    "aurelia-binding": "npm:aurelia-binding@1.2.0",
    "aurelia-bootstrapper": "npm:aurelia-bootstrapper@1.0.1",
    "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.3.0",
    "aurelia-event-aggregator": "npm:aurelia-event-aggregator@1.0.1",
    "aurelia-fetch-client": "npm:aurelia-fetch-client@1.1.1",
    "aurelia-framework": "npm:aurelia-framework@1.1.0",
    "aurelia-history": "npm:aurelia-history@1.0.0",
    "aurelia-history-browser": "npm:aurelia-history-browser@1.0.0",
    "aurelia-http-client": "npm:aurelia-http-client@1.0.4",
    "aurelia-kendoui-bridge": "npm:aurelia-kendoui-bridge@1.2.1",
    "aurelia-loader": "npm:aurelia-loader@1.0.0",
    "aurelia-loader-default": "npm:aurelia-loader-default@1.0.1",
    "aurelia-logging": "npm:aurelia-logging@1.3.0",
    "aurelia-logging-console": "npm:aurelia-logging-console@1.0.0",
    "aurelia-metadata": "npm:aurelia-metadata@1.0.3",
    "aurelia-path": "npm:aurelia-path@1.1.1",
    "aurelia-route-recognizer": "npm:aurelia-route-recognizer@1.1.0",
    "aurelia-router": "npm:aurelia-router@1.2.1",
    "aurelia-task-queue": "npm:aurelia-task-queue@1.2.0",
    "aurelia-templating": "npm:aurelia-templating@1.3.0",
    "aurelia-templating-binding": "npm:aurelia-templating-binding@1.3.0",
    "aurelia-templating-resources": "npm:aurelia-templating-resources@1.3.1",
    "aurelia-templating-router": "npm:aurelia-templating-router@1.1.0",
    "babel": "npm:babel-core@5.8.38",
    "babel-runtime": "npm:babel-runtime@5.8.38",
    "core-js": "npm:core-js@0.9.18",
    "css": "github:systemjs/plugin-css@0.1.33",
    "json": "github:systemjs/plugin-json@0.1.2",
    "text": "github:systemjs/plugin-text@0.0.7",
    "github:aurelia-ui-toolkits/aurelia-after-attached-plugin@0.1.3": {
      "aurelia-task-queue": "npm:aurelia-task-queue@1.2.0",
      "aurelia-templating": "npm:aurelia-templating@1.3.0"
    },
    "github:jspm/nodelibs-assert@0.1.0": {
      "assert": "npm:assert@1.4.1"
    },
    "github:jspm/nodelibs-buffer@0.1.0": {
      "buffer": "npm:buffer@3.6.0"
    },
    "github:jspm/nodelibs-process@0.1.2": {
      "process": "npm:process@0.11.9"
    },
    "github:jspm/nodelibs-util@0.1.0": {
      "util": "npm:util@0.10.3"
    },
    "github:jspm/nodelibs-vm@0.1.0": {
      "vm-browserify": "npm:vm-browserify@0.0.4"
    },
    "npm:assert@1.4.1": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "util": "npm:util@0.10.3"
    },
    "npm:aurelia-animator-css@1.0.1": {
      "aurelia-metadata": "npm:aurelia-metadata@1.0.3",
      "aurelia-pal": "npm:aurelia-pal@1.3.0",
      "aurelia-templating": "npm:aurelia-templating@1.3.0"
    },
    "npm:aurelia-binding@1.2.0": {
      "aurelia-logging": "npm:aurelia-logging@1.3.0",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.3",
      "aurelia-pal": "npm:aurelia-pal@1.3.0",
      "aurelia-task-queue": "npm:aurelia-task-queue@1.2.0"
    },
    "npm:aurelia-bootstrapper@1.0.1": {
      "aurelia-event-aggregator": "npm:aurelia-event-aggregator@1.0.1",
      "aurelia-framework": "npm:aurelia-framework@1.1.0",
      "aurelia-history": "npm:aurelia-history@1.0.0",
      "aurelia-history-browser": "npm:aurelia-history-browser@1.0.0",
      "aurelia-loader-default": "npm:aurelia-loader-default@1.0.1",
      "aurelia-logging-console": "npm:aurelia-logging-console@1.0.0",
      "aurelia-pal": "npm:aurelia-pal@1.3.0",
      "aurelia-pal-browser": "npm:aurelia-pal-browser@1.1.0",
      "aurelia-polyfills": "npm:aurelia-polyfills@1.2.0",
      "aurelia-router": "npm:aurelia-router@1.2.1",
      "aurelia-templating": "npm:aurelia-templating@1.3.0",
      "aurelia-templating-binding": "npm:aurelia-templating-binding@1.3.0",
      "aurelia-templating-resources": "npm:aurelia-templating-resources@1.3.1",
      "aurelia-templating-router": "npm:aurelia-templating-router@1.1.0"
    },
    "npm:aurelia-dependency-injection@1.3.0": {
      "aurelia-metadata": "npm:aurelia-metadata@1.0.3",
      "aurelia-pal": "npm:aurelia-pal@1.3.0"
    },
    "npm:aurelia-event-aggregator@1.0.1": {
      "aurelia-logging": "npm:aurelia-logging@1.3.0"
    },
    "npm:aurelia-framework@1.1.0": {
      "aurelia-binding": "npm:aurelia-binding@1.2.0",
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.3.0",
      "aurelia-loader": "npm:aurelia-loader@1.0.0",
      "aurelia-logging": "npm:aurelia-logging@1.3.0",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.3",
      "aurelia-pal": "npm:aurelia-pal@1.3.0",
      "aurelia-path": "npm:aurelia-path@1.1.1",
      "aurelia-task-queue": "npm:aurelia-task-queue@1.2.0",
      "aurelia-templating": "npm:aurelia-templating@1.3.0"
    },
    "npm:aurelia-history-browser@1.0.0": {
      "aurelia-history": "npm:aurelia-history@1.0.0",
      "aurelia-pal": "npm:aurelia-pal@1.3.0"
    },
    "npm:aurelia-http-client@1.0.4": {
      "aurelia-pal": "npm:aurelia-pal@1.3.0",
      "aurelia-path": "npm:aurelia-path@1.1.1"
    },
    "npm:aurelia-kendoui-bridge@1.2.1": {
      "aurelia-binding": "npm:aurelia-binding@1.2.0",
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.3.0",
      "aurelia-logging": "npm:aurelia-logging@1.3.0",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.3",
      "aurelia-router": "npm:aurelia-router@1.2.1",
      "aurelia-task-queue": "npm:aurelia-task-queue@1.2.0",
      "aurelia-templating": "npm:aurelia-templating@1.3.0",
      "aurelia-templating-resources": "npm:aurelia-templating-resources@1.3.1"
    },
    "npm:aurelia-loader-default@1.0.1": {
      "aurelia-loader": "npm:aurelia-loader@1.0.0",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.3",
      "aurelia-pal": "npm:aurelia-pal@1.3.0"
    },
    "npm:aurelia-loader@1.0.0": {
      "aurelia-metadata": "npm:aurelia-metadata@1.0.3",
      "aurelia-path": "npm:aurelia-path@1.1.1"
    },
    "npm:aurelia-logging-console@1.0.0": {
      "aurelia-logging": "npm:aurelia-logging@1.3.0"
    },
    "npm:aurelia-metadata@1.0.3": {
      "aurelia-pal": "npm:aurelia-pal@1.3.0"
    },
    "npm:aurelia-pal-browser@1.1.0": {
      "aurelia-pal": "npm:aurelia-pal@1.3.0"
    },
    "npm:aurelia-polyfills@1.2.0": {
      "aurelia-pal": "npm:aurelia-pal@1.3.0"
    },
    "npm:aurelia-route-recognizer@1.1.0": {
      "aurelia-path": "npm:aurelia-path@1.1.1"
    },
    "npm:aurelia-router@1.2.1": {
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.3.0",
      "aurelia-event-aggregator": "npm:aurelia-event-aggregator@1.0.1",
      "aurelia-history": "npm:aurelia-history@1.0.0",
      "aurelia-logging": "npm:aurelia-logging@1.3.0",
      "aurelia-path": "npm:aurelia-path@1.1.1",
      "aurelia-route-recognizer": "npm:aurelia-route-recognizer@1.1.0"
    },
    "npm:aurelia-task-queue@1.2.0": {
      "aurelia-pal": "npm:aurelia-pal@1.3.0"
    },
    "npm:aurelia-templating-binding@1.3.0": {
      "aurelia-binding": "npm:aurelia-binding@1.2.0",
      "aurelia-logging": "npm:aurelia-logging@1.3.0",
      "aurelia-templating": "npm:aurelia-templating@1.3.0"
    },
    "npm:aurelia-templating-resources@1.3.1": {
      "aurelia-binding": "npm:aurelia-binding@1.2.0",
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.3.0",
      "aurelia-loader": "npm:aurelia-loader@1.0.0",
      "aurelia-logging": "npm:aurelia-logging@1.3.0",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.3",
      "aurelia-pal": "npm:aurelia-pal@1.3.0",
      "aurelia-path": "npm:aurelia-path@1.1.1",
      "aurelia-task-queue": "npm:aurelia-task-queue@1.2.0",
      "aurelia-templating": "npm:aurelia-templating@1.3.0"
    },
    "npm:aurelia-templating-router@1.1.0": {
      "aurelia-binding": "npm:aurelia-binding@1.2.0",
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.3.0",
      "aurelia-logging": "npm:aurelia-logging@1.3.0",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.3",
      "aurelia-pal": "npm:aurelia-pal@1.3.0",
      "aurelia-path": "npm:aurelia-path@1.1.1",
      "aurelia-router": "npm:aurelia-router@1.2.1",
      "aurelia-templating": "npm:aurelia-templating@1.3.0"
    },
    "npm:aurelia-templating@1.3.0": {
      "aurelia-binding": "npm:aurelia-binding@1.2.0",
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.3.0",
      "aurelia-loader": "npm:aurelia-loader@1.0.0",
      "aurelia-logging": "npm:aurelia-logging@1.3.0",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.3",
      "aurelia-pal": "npm:aurelia-pal@1.3.0",
      "aurelia-path": "npm:aurelia-path@1.1.1",
      "aurelia-task-queue": "npm:aurelia-task-queue@1.2.0"
    },
    "npm:babel-runtime@5.8.38": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:buffer@3.6.0": {
      "base64-js": "npm:base64-js@0.0.8",
      "child_process": "github:jspm/nodelibs-child_process@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "ieee754": "npm:ieee754@1.1.8",
      "isarray": "npm:isarray@1.0.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:core-js@0.9.18": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:inherits@2.0.1": {
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:process@0.11.9": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "vm": "github:jspm/nodelibs-vm@0.1.0"
    },
    "npm:util@0.10.3": {
      "inherits": "npm:inherits@2.0.1",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:vm-browserify@0.0.4": {
      "indexof": "npm:indexof@0.0.1"
    }
  },
  bundles: {
    "bundles/bundle.js": [
      "github:aurelia-ui-toolkits/aurelia-after-attached-plugin@0.1.3.js",
      "github:aurelia-ui-toolkits/aurelia-after-attached-plugin@0.1.3/aurelia-after-attached-plugin.js",
      "github:aurelia-ui-toolkits/aurelia-after-attached-plugin@0.1.3/index.js",
      "github:systemjs/plugin-css@0.1.33.js",
      "github:systemjs/plugin-css@0.1.33/css.js",
      "github:systemjs/plugin-json@0.1.2.js",
      "github:systemjs/plugin-json@0.1.2/json.js",
      "github:systemjs/plugin-text@0.0.7.js",
      "github:systemjs/plugin-text@0.0.7/text.js",
      "npm:aurelia-animator-css@1.0.1.js",
      "npm:aurelia-animator-css@1.0.1/aurelia-animator-css.js",
      "npm:aurelia-binding@1.2.0.js",
      "npm:aurelia-binding@1.2.0/aurelia-binding.js",
      "npm:aurelia-bootstrapper@1.0.1.js",
      "npm:aurelia-bootstrapper@1.0.1/aurelia-bootstrapper.js",
      "npm:aurelia-dependency-injection@1.3.0.js",
      "npm:aurelia-dependency-injection@1.3.0/aurelia-dependency-injection.js",
      "npm:aurelia-event-aggregator@1.0.1.js",
      "npm:aurelia-event-aggregator@1.0.1/aurelia-event-aggregator.js",
      "npm:aurelia-fetch-client@1.1.1.js",
      "npm:aurelia-fetch-client@1.1.1/aurelia-fetch-client.js",
      "npm:aurelia-framework@1.1.0.js",
      "npm:aurelia-framework@1.1.0/aurelia-framework.js",
      "npm:aurelia-history-browser@1.0.0.js",
      "npm:aurelia-history-browser@1.0.0/aurelia-history-browser.js",
      "npm:aurelia-history@1.0.0.js",
      "npm:aurelia-history@1.0.0/aurelia-history.js",
      "npm:aurelia-http-client@1.0.4.js",
      "npm:aurelia-http-client@1.0.4/aurelia-http-client.js",
      "npm:aurelia-kendoui-bridge@1.2.1.js",
      "npm:aurelia-kendoui-bridge@1.2.1/autocomplete/autocomplete.html!github:systemjs/plugin-text@0.0.7.js",
      "npm:aurelia-kendoui-bridge@1.2.1/autocomplete/autocomplete.js",
      "npm:aurelia-kendoui-bridge@1.2.1/barcode/barcode.js",
      "npm:aurelia-kendoui-bridge@1.2.1/button/button.js",
      "npm:aurelia-kendoui-bridge@1.2.1/buttongroup/buttongroup.js",
      "npm:aurelia-kendoui-bridge@1.2.1/calendar/calendar.html!github:systemjs/plugin-text@0.0.7.js",
      "npm:aurelia-kendoui-bridge@1.2.1/calendar/calendar.js",
      "npm:aurelia-kendoui-bridge@1.2.1/chart/chart.html!github:systemjs/plugin-text@0.0.7.js",
      "npm:aurelia-kendoui-bridge@1.2.1/chart/chart.js",
      "npm:aurelia-kendoui-bridge@1.2.1/chart/sparkline.html!github:systemjs/plugin-text@0.0.7.js",
      "npm:aurelia-kendoui-bridge@1.2.1/chart/sparkline.js",
      "npm:aurelia-kendoui-bridge@1.2.1/chart/stock.html!github:systemjs/plugin-text@0.0.7.js",
      "npm:aurelia-kendoui-bridge@1.2.1/chart/stock.js",
      "npm:aurelia-kendoui-bridge@1.2.1/chart/treemap.html!github:systemjs/plugin-text@0.0.7.js",
      "npm:aurelia-kendoui-bridge@1.2.1/chart/treemap.js",
      "npm:aurelia-kendoui-bridge@1.2.1/colorpalette/colorpalette.html!github:systemjs/plugin-text@0.0.7.js",
      "npm:aurelia-kendoui-bridge@1.2.1/colorpalette/colorpalette.js",
      "npm:aurelia-kendoui-bridge@1.2.1/colorpicker/colorpicker.js",
      "npm:aurelia-kendoui-bridge@1.2.1/combobox/combobox.html!github:systemjs/plugin-text@0.0.7.js",
      "npm:aurelia-kendoui-bridge@1.2.1/combobox/combobox.js",
      "npm:aurelia-kendoui-bridge@1.2.1/common/bindables.js",
      "npm:aurelia-kendoui-bridge@1.2.1/common/constants.js",
      "npm:aurelia-kendoui-bridge@1.2.1/common/control-properties.js",
      "npm:aurelia-kendoui-bridge@1.2.1/common/decorators.js",
      "npm:aurelia-kendoui-bridge@1.2.1/common/notify-binding-behavior.js",
      "npm:aurelia-kendoui-bridge@1.2.1/common/options-builder.js",
      "npm:aurelia-kendoui-bridge@1.2.1/common/template-compiler.js",
      "npm:aurelia-kendoui-bridge@1.2.1/common/template-gatherer.js",
      "npm:aurelia-kendoui-bridge@1.2.1/common/template.js",
      "npm:aurelia-kendoui-bridge@1.2.1/common/util.js",
      "npm:aurelia-kendoui-bridge@1.2.1/common/widget-base.js",
      "npm:aurelia-kendoui-bridge@1.2.1/config-builder.js",
      "npm:aurelia-kendoui-bridge@1.2.1/contextmenu/contextmenu.js",
      "npm:aurelia-kendoui-bridge@1.2.1/datepicker/datepicker.js",
      "npm:aurelia-kendoui-bridge@1.2.1/datetimepicker/datetimepicker.js",
      "npm:aurelia-kendoui-bridge@1.2.1/diagram/diagram.html!github:systemjs/plugin-text@0.0.7.js",
      "npm:aurelia-kendoui-bridge@1.2.1/diagram/diagram.js",
      "npm:aurelia-kendoui-bridge@1.2.1/dialog/dialog.js",
      "npm:aurelia-kendoui-bridge@1.2.1/draggable/draggable.js",
      "npm:aurelia-kendoui-bridge@1.2.1/drop-target/drop-target-area.js",
      "npm:aurelia-kendoui-bridge@1.2.1/drop-target/drop-target.js",
      "npm:aurelia-kendoui-bridge@1.2.1/dropdownlist/dropdownlist.html!github:systemjs/plugin-text@0.0.7.js",
      "npm:aurelia-kendoui-bridge@1.2.1/dropdownlist/dropdownlist.js",
      "npm:aurelia-kendoui-bridge@1.2.1/editor/editor.js",
      "npm:aurelia-kendoui-bridge@1.2.1/filter-menu/filter-menu.js",
      "npm:aurelia-kendoui-bridge@1.2.1/flatcolorpicker/flatcolorpicker.html!github:systemjs/plugin-text@0.0.7.js",
      "npm:aurelia-kendoui-bridge@1.2.1/flatcolorpicker/flatcolorpicker.js",
      "npm:aurelia-kendoui-bridge@1.2.1/gantt/gantt-col.html!github:systemjs/plugin-text@0.0.7.js",
      "npm:aurelia-kendoui-bridge@1.2.1/gantt/gantt-col.js",
      "npm:aurelia-kendoui-bridge@1.2.1/gantt/gantt.html!github:systemjs/plugin-text@0.0.7.js",
      "npm:aurelia-kendoui-bridge@1.2.1/gantt/gantt.js",
      "npm:aurelia-kendoui-bridge@1.2.1/gauges/linear-gauge.html!github:systemjs/plugin-text@0.0.7.js",
      "npm:aurelia-kendoui-bridge@1.2.1/gauges/linear-gauge.js",
      "npm:aurelia-kendoui-bridge@1.2.1/gauges/radial-gauge.html!github:systemjs/plugin-text@0.0.7.js",
      "npm:aurelia-kendoui-bridge@1.2.1/gauges/radial-gauge.js",
      "npm:aurelia-kendoui-bridge@1.2.1/grid/col.html!github:systemjs/plugin-text@0.0.7.js",
      "npm:aurelia-kendoui-bridge@1.2.1/grid/col.js",
      "npm:aurelia-kendoui-bridge@1.2.1/grid/grid-command.html!github:systemjs/plugin-text@0.0.7.js",
      "npm:aurelia-kendoui-bridge@1.2.1/grid/grid-command.js",
      "npm:aurelia-kendoui-bridge@1.2.1/grid/grid-toolbar.html!github:systemjs/plugin-text@0.0.7.js",
      "npm:aurelia-kendoui-bridge@1.2.1/grid/grid-toolbar.js",
      "npm:aurelia-kendoui-bridge@1.2.1/grid/grid.html!github:systemjs/plugin-text@0.0.7.js",
      "npm:aurelia-kendoui-bridge@1.2.1/grid/grid.js",
      "npm:aurelia-kendoui-bridge@1.2.1/index.js",
      "npm:aurelia-kendoui-bridge@1.2.1/listview/listview.html!github:systemjs/plugin-text@0.0.7.js",
      "npm:aurelia-kendoui-bridge@1.2.1/listview/listview.js",
      "npm:aurelia-kendoui-bridge@1.2.1/map/map.html!github:systemjs/plugin-text@0.0.7.js",
      "npm:aurelia-kendoui-bridge@1.2.1/map/map.js",
      "npm:aurelia-kendoui-bridge@1.2.1/maskedtextbox/maskedtextbox.js",
      "npm:aurelia-kendoui-bridge@1.2.1/menu/menu.js",
      "npm:aurelia-kendoui-bridge@1.2.1/multiselect/multiselect.html!github:systemjs/plugin-text@0.0.7.js",
      "npm:aurelia-kendoui-bridge@1.2.1/multiselect/multiselect.js",
      "npm:aurelia-kendoui-bridge@1.2.1/notification/notification-template.js",
      "npm:aurelia-kendoui-bridge@1.2.1/notification/notification.html!github:systemjs/plugin-text@0.0.7.js",
      "npm:aurelia-kendoui-bridge@1.2.1/notification/notification.js",
      "npm:aurelia-kendoui-bridge@1.2.1/numerictextbox/numerictextbox.js",
      "npm:aurelia-kendoui-bridge@1.2.1/panelbar/panelbar.html!github:systemjs/plugin-text@0.0.7.js",
      "npm:aurelia-kendoui-bridge@1.2.1/panelbar/panelbar.js",
      "npm:aurelia-kendoui-bridge@1.2.1/pdf/pdf.js",
      "npm:aurelia-kendoui-bridge@1.2.1/pivotgrid/pivotconfigurator.html!github:systemjs/plugin-text@0.0.7.js",
      "npm:aurelia-kendoui-bridge@1.2.1/pivotgrid/pivotconfigurator.js",
      "npm:aurelia-kendoui-bridge@1.2.1/pivotgrid/pivotgrid.html!github:systemjs/plugin-text@0.0.7.js",
      "npm:aurelia-kendoui-bridge@1.2.1/pivotgrid/pivotgrid.js",
      "npm:aurelia-kendoui-bridge@1.2.1/popup/popup.js",
      "npm:aurelia-kendoui-bridge@1.2.1/progressbar/progressbar.js",
      "npm:aurelia-kendoui-bridge@1.2.1/qrcode/qrcode.js",
      "npm:aurelia-kendoui-bridge@1.2.1/rangeslider/rangeslider.html!github:systemjs/plugin-text@0.0.7.js",
      "npm:aurelia-kendoui-bridge@1.2.1/rangeslider/rangeslider.js",
      "npm:aurelia-kendoui-bridge@1.2.1/responsivepanel/responsivepanel.js",
      "npm:aurelia-kendoui-bridge@1.2.1/scheduler/scheduler.html!github:systemjs/plugin-text@0.0.7.js",
      "npm:aurelia-kendoui-bridge@1.2.1/scheduler/scheduler.js",
      "npm:aurelia-kendoui-bridge@1.2.1/scrollview/scrollview.html!github:systemjs/plugin-text@0.0.7.js",
      "npm:aurelia-kendoui-bridge@1.2.1/scrollview/scrollview.js",
      "npm:aurelia-kendoui-bridge@1.2.1/slider/slider.js",
      "npm:aurelia-kendoui-bridge@1.2.1/sortable/sortable.js",
      "npm:aurelia-kendoui-bridge@1.2.1/splitter/splitter.js",
      "npm:aurelia-kendoui-bridge@1.2.1/spreadsheet/spreadsheet.html!github:systemjs/plugin-text@0.0.7.js",
      "npm:aurelia-kendoui-bridge@1.2.1/spreadsheet/spreadsheet.js",
      "npm:aurelia-kendoui-bridge@1.2.1/switch/switch.js",
      "npm:aurelia-kendoui-bridge@1.2.1/tabstrip/tabstrip.js",
      "npm:aurelia-kendoui-bridge@1.2.1/timepicker/timepicker.js",
      "npm:aurelia-kendoui-bridge@1.2.1/toolbar/toolbar-item-button.html!github:systemjs/plugin-text@0.0.7.js",
      "npm:aurelia-kendoui-bridge@1.2.1/toolbar/toolbar-item-button.js",
      "npm:aurelia-kendoui-bridge@1.2.1/toolbar/toolbar-item.html!github:systemjs/plugin-text@0.0.7.js",
      "npm:aurelia-kendoui-bridge@1.2.1/toolbar/toolbar-item.js",
      "npm:aurelia-kendoui-bridge@1.2.1/toolbar/toolbar.html!github:systemjs/plugin-text@0.0.7.js",
      "npm:aurelia-kendoui-bridge@1.2.1/toolbar/toolbar.js",
      "npm:aurelia-kendoui-bridge@1.2.1/tooltip/tooltip.js",
      "npm:aurelia-kendoui-bridge@1.2.1/treelist/tree-col.html!github:systemjs/plugin-text@0.0.7.js",
      "npm:aurelia-kendoui-bridge@1.2.1/treelist/tree-col.js",
      "npm:aurelia-kendoui-bridge@1.2.1/treelist/treelist.html!github:systemjs/plugin-text@0.0.7.js",
      "npm:aurelia-kendoui-bridge@1.2.1/treelist/treelist.js",
      "npm:aurelia-kendoui-bridge@1.2.1/treeview/treeview.html!github:systemjs/plugin-text@0.0.7.js",
      "npm:aurelia-kendoui-bridge@1.2.1/treeview/treeview.js",
      "npm:aurelia-kendoui-bridge@1.2.1/upload/upload.html!github:systemjs/plugin-text@0.0.7.js",
      "npm:aurelia-kendoui-bridge@1.2.1/upload/upload.js",
      "npm:aurelia-kendoui-bridge@1.2.1/validator/validator.js",
      "npm:aurelia-kendoui-bridge@1.2.1/valueconverters/valueconverters.js",
      "npm:aurelia-kendoui-bridge@1.2.1/version.js",
      "npm:aurelia-kendoui-bridge@1.2.1/window/window.js",
      "npm:aurelia-loader-default@1.0.1.js",
      "npm:aurelia-loader-default@1.0.1/aurelia-loader-default.js",
      "npm:aurelia-loader@1.0.0.js",
      "npm:aurelia-loader@1.0.0/aurelia-loader.js",
      "npm:aurelia-logging-console@1.0.0.js",
      "npm:aurelia-logging-console@1.0.0/aurelia-logging-console.js",
      "npm:aurelia-logging@1.3.0.js",
      "npm:aurelia-logging@1.3.0/aurelia-logging.js",
      "npm:aurelia-metadata@1.0.3.js",
      "npm:aurelia-metadata@1.0.3/aurelia-metadata.js",
      "npm:aurelia-pal-browser@1.1.0.js",
      "npm:aurelia-pal-browser@1.1.0/aurelia-pal-browser.js",
      "npm:aurelia-pal@1.3.0.js",
      "npm:aurelia-pal@1.3.0/aurelia-pal.js",
      "npm:aurelia-path@1.1.1.js",
      "npm:aurelia-path@1.1.1/aurelia-path.js",
      "npm:aurelia-polyfills@1.2.0.js",
      "npm:aurelia-polyfills@1.2.0/aurelia-polyfills.js",
      "npm:aurelia-route-recognizer@1.1.0.js",
      "npm:aurelia-route-recognizer@1.1.0/aurelia-route-recognizer.js",
      "npm:aurelia-router@1.2.1.js",
      "npm:aurelia-router@1.2.1/aurelia-router.js",
      "npm:aurelia-task-queue@1.2.0.js",
      "npm:aurelia-task-queue@1.2.0/aurelia-task-queue.js",
      "npm:aurelia-templating-binding@1.3.0.js",
      "npm:aurelia-templating-binding@1.3.0/aurelia-templating-binding.js",
      "npm:aurelia-templating-resources@1.3.1.js",
      "npm:aurelia-templating-resources@1.3.1/abstract-repeater.js",
      "npm:aurelia-templating-resources@1.3.1/analyze-view-factory.js",
      "npm:aurelia-templating-resources@1.3.1/array-repeat-strategy.js",
      "npm:aurelia-templating-resources@1.3.1/attr-binding-behavior.js",
      "npm:aurelia-templating-resources@1.3.1/aurelia-hide-style.js",
      "npm:aurelia-templating-resources@1.3.1/aurelia-templating-resources.js",
      "npm:aurelia-templating-resources@1.3.1/binding-mode-behaviors.js",
      "npm:aurelia-templating-resources@1.3.1/binding-signaler.js",
      "npm:aurelia-templating-resources@1.3.1/compose.js",
      "npm:aurelia-templating-resources@1.3.1/css-resource.js",
      "npm:aurelia-templating-resources@1.3.1/debounce-binding-behavior.js",
      "npm:aurelia-templating-resources@1.3.1/dynamic-element.js",
      "npm:aurelia-templating-resources@1.3.1/focus.js",
      "npm:aurelia-templating-resources@1.3.1/hide.js",
      "npm:aurelia-templating-resources@1.3.1/html-resource-plugin.js",
      "npm:aurelia-templating-resources@1.3.1/html-sanitizer.js",
      "npm:aurelia-templating-resources@1.3.1/if.js",
      "npm:aurelia-templating-resources@1.3.1/map-repeat-strategy.js",
      "npm:aurelia-templating-resources@1.3.1/null-repeat-strategy.js",
      "npm:aurelia-templating-resources@1.3.1/number-repeat-strategy.js",
      "npm:aurelia-templating-resources@1.3.1/repeat-strategy-locator.js",
      "npm:aurelia-templating-resources@1.3.1/repeat-utilities.js",
      "npm:aurelia-templating-resources@1.3.1/repeat.js",
      "npm:aurelia-templating-resources@1.3.1/replaceable.js",
      "npm:aurelia-templating-resources@1.3.1/sanitize-html.js",
      "npm:aurelia-templating-resources@1.3.1/self-binding-behavior.js",
      "npm:aurelia-templating-resources@1.3.1/set-repeat-strategy.js",
      "npm:aurelia-templating-resources@1.3.1/show.js",
      "npm:aurelia-templating-resources@1.3.1/signal-binding-behavior.js",
      "npm:aurelia-templating-resources@1.3.1/throttle-binding-behavior.js",
      "npm:aurelia-templating-resources@1.3.1/update-trigger-binding-behavior.js",
      "npm:aurelia-templating-resources@1.3.1/with.js",
      "npm:aurelia-templating-router@1.1.0.js",
      "npm:aurelia-templating-router@1.1.0/aurelia-templating-router.js",
      "npm:aurelia-templating-router@1.1.0/route-href.js",
      "npm:aurelia-templating-router@1.1.0/route-loader.js",
      "npm:aurelia-templating-router@1.1.0/router-view.js",
      "npm:aurelia-templating@1.3.0.js",
      "npm:aurelia-templating@1.3.0/aurelia-templating.js"
    ]
  }
});