System.config({
  defaultJSExtensions: true,
  transpiler: "babel",
  babelOptions: {
    "ignore": [
      "github:*",
      "npm:*"
    ],
    "stage": 0,
    "optional": []
  },
  paths: {
    "github:*": "https://cdn.rawgit.com/aurelia-ui-toolkits/aurelia-kendoui-bundles/0.3.20/jspm_packages/github/*",
    "npm:*": "https://cdn.rawgit.com/aurelia-ui-toolkits/aurelia-kendoui-bundles/0.3.20/jspm_packages/npm/*",
    "bundles/bundle.js": "https://cdn.rawgit.com/aurelia-ui-toolkits/aurelia-kendoui-bundles/0.3.20/bundles/bundle.js"
  },
  map: {
    "aurelia-animator-css": "npm:aurelia-animator-css@1.0.0",
    "aurelia-binding": "npm:aurelia-binding@1.0.1",
    "aurelia-bootstrapper": "npm:aurelia-bootstrapper@1.0.0",
    "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.0.0",
    "aurelia-event-aggregator": "npm:aurelia-event-aggregator@1.0.0",
    "aurelia-fetch-client": "npm:aurelia-fetch-client@1.0.0",
    "aurelia-framework": "npm:aurelia-framework@1.0.1",
    "aurelia-history": "npm:aurelia-history@1.0.0",
    "aurelia-history-browser": "npm:aurelia-history-browser@1.0.0",
    "aurelia-http-client": "npm:aurelia-http-client@1.0.0",
    "aurelia-kendoui-bridge": "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta",
    "aurelia-loader": "npm:aurelia-loader@1.0.0",
    "aurelia-loader-default": "npm:aurelia-loader-default@1.0.0",
    "aurelia-logging": "npm:aurelia-logging@1.0.0",
    "aurelia-logging-console": "npm:aurelia-logging-console@1.0.0",
    "aurelia-metadata": "npm:aurelia-metadata@1.0.0",
    "aurelia-path": "npm:aurelia-path@1.0.0",
    "aurelia-route-recognizer": "npm:aurelia-route-recognizer@1.0.0",
    "aurelia-router": "npm:aurelia-router@1.0.2",
    "aurelia-task-queue": "npm:aurelia-task-queue@1.0.0",
    "aurelia-templating": "npm:aurelia-templating@1.0.0",
    "aurelia-templating-binding": "npm:aurelia-templating-binding@1.0.0",
    "aurelia-templating-resources": "npm:aurelia-templating-resources@1.0.0",
    "aurelia-templating-router": "npm:aurelia-templating-router@1.0.0",
    "babel": "npm:babel-core@5.8.38",
    "babel-runtime": "npm:babel-runtime@5.8.38",
    "core-js": "npm:core-js@0.9.18",
    "json": "github:systemjs/plugin-json@0.1.2",
    "text": "github:systemjs/plugin-text@0.0.7",
    "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta": {
      "aurelia-binding": "npm:aurelia-binding@1.0.1",
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.0.0",
      "aurelia-logging": "npm:aurelia-logging@1.0.0",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0",
      "aurelia-task-queue": "npm:aurelia-task-queue@1.0.0",
      "aurelia-templating": "npm:aurelia-templating@1.0.0",
      "aurelia-templating-resources": "npm:aurelia-templating-resources@1.0.0"
    },
    "github:jspm/nodelibs-assert@0.1.0": {
      "assert": "npm:assert@1.4.1"
    },
    "github:jspm/nodelibs-buffer@0.1.0": {
      "buffer": "npm:buffer@3.6.0"
    },
    "github:jspm/nodelibs-process@0.1.2": {
      "process": "npm:process@0.11.6"
    },
    "github:jspm/nodelibs-util@0.1.0": {
      "util": "npm:util@0.10.3"
    },
    "github:jspm/nodelibs-vm@0.1.0": {
      "vm-browserify": "npm:vm-browserify@0.0.4"
    },
    "npm:assert@1.4.1": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "util": "npm:util@0.10.3"
    },
    "npm:aurelia-animator-css@1.0.0": {
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0",
      "aurelia-pal": "npm:aurelia-pal@1.0.0",
      "aurelia-templating": "npm:aurelia-templating@1.0.0"
    },
    "npm:aurelia-binding@1.0.1": {
      "aurelia-logging": "npm:aurelia-logging@1.0.0",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0",
      "aurelia-pal": "npm:aurelia-pal@1.0.0",
      "aurelia-task-queue": "npm:aurelia-task-queue@1.0.0"
    },
    "npm:aurelia-bootstrapper@1.0.0": {
      "aurelia-event-aggregator": "npm:aurelia-event-aggregator@1.0.0",
      "aurelia-framework": "npm:aurelia-framework@1.0.1",
      "aurelia-history": "npm:aurelia-history@1.0.0",
      "aurelia-history-browser": "npm:aurelia-history-browser@1.0.0",
      "aurelia-loader-default": "npm:aurelia-loader-default@1.0.0",
      "aurelia-logging-console": "npm:aurelia-logging-console@1.0.0",
      "aurelia-pal": "npm:aurelia-pal@1.0.0",
      "aurelia-pal-browser": "npm:aurelia-pal-browser@1.0.0",
      "aurelia-polyfills": "npm:aurelia-polyfills@1.0.0",
      "aurelia-router": "npm:aurelia-router@1.0.2",
      "aurelia-templating": "npm:aurelia-templating@1.0.0",
      "aurelia-templating-binding": "npm:aurelia-templating-binding@1.0.0",
      "aurelia-templating-resources": "npm:aurelia-templating-resources@1.0.0",
      "aurelia-templating-router": "npm:aurelia-templating-router@1.0.0"
    },
    "npm:aurelia-dependency-injection@1.0.0": {
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0",
      "aurelia-pal": "npm:aurelia-pal@1.0.0"
    },
    "npm:aurelia-event-aggregator@1.0.0": {
      "aurelia-logging": "npm:aurelia-logging@1.0.0"
    },
    "npm:aurelia-framework@1.0.1": {
      "aurelia-binding": "npm:aurelia-binding@1.0.1",
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.0.0",
      "aurelia-loader": "npm:aurelia-loader@1.0.0",
      "aurelia-logging": "npm:aurelia-logging@1.0.0",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0",
      "aurelia-pal": "npm:aurelia-pal@1.0.0",
      "aurelia-path": "npm:aurelia-path@1.0.0",
      "aurelia-task-queue": "npm:aurelia-task-queue@1.0.0",
      "aurelia-templating": "npm:aurelia-templating@1.0.0"
    },
    "npm:aurelia-history-browser@1.0.0": {
      "aurelia-history": "npm:aurelia-history@1.0.0",
      "aurelia-pal": "npm:aurelia-pal@1.0.0"
    },
    "npm:aurelia-http-client@1.0.0": {
      "aurelia-pal": "npm:aurelia-pal@1.0.0",
      "aurelia-path": "npm:aurelia-path@1.0.0"
    },
    "npm:aurelia-loader-default@1.0.0": {
      "aurelia-loader": "npm:aurelia-loader@1.0.0",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0",
      "aurelia-pal": "npm:aurelia-pal@1.0.0"
    },
    "npm:aurelia-loader@1.0.0": {
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0",
      "aurelia-path": "npm:aurelia-path@1.0.0"
    },
    "npm:aurelia-logging-console@1.0.0": {
      "aurelia-logging": "npm:aurelia-logging@1.0.0"
    },
    "npm:aurelia-metadata@1.0.0": {
      "aurelia-pal": "npm:aurelia-pal@1.0.0"
    },
    "npm:aurelia-pal-browser@1.0.0": {
      "aurelia-pal": "npm:aurelia-pal@1.0.0"
    },
    "npm:aurelia-polyfills@1.0.0": {
      "aurelia-pal": "npm:aurelia-pal@1.0.0"
    },
    "npm:aurelia-route-recognizer@1.0.0": {
      "aurelia-path": "npm:aurelia-path@1.0.0"
    },
    "npm:aurelia-router@1.0.2": {
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.0.0",
      "aurelia-event-aggregator": "npm:aurelia-event-aggregator@1.0.0",
      "aurelia-history": "npm:aurelia-history@1.0.0",
      "aurelia-logging": "npm:aurelia-logging@1.0.0",
      "aurelia-path": "npm:aurelia-path@1.0.0",
      "aurelia-route-recognizer": "npm:aurelia-route-recognizer@1.0.0"
    },
    "npm:aurelia-task-queue@1.0.0": {
      "aurelia-pal": "npm:aurelia-pal@1.0.0"
    },
    "npm:aurelia-templating-binding@1.0.0": {
      "aurelia-binding": "npm:aurelia-binding@1.0.1",
      "aurelia-logging": "npm:aurelia-logging@1.0.0",
      "aurelia-templating": "npm:aurelia-templating@1.0.0"
    },
    "npm:aurelia-templating-resources@1.0.0": {
      "aurelia-binding": "npm:aurelia-binding@1.0.1",
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.0.0",
      "aurelia-loader": "npm:aurelia-loader@1.0.0",
      "aurelia-logging": "npm:aurelia-logging@1.0.0",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0",
      "aurelia-pal": "npm:aurelia-pal@1.0.0",
      "aurelia-path": "npm:aurelia-path@1.0.0",
      "aurelia-task-queue": "npm:aurelia-task-queue@1.0.0",
      "aurelia-templating": "npm:aurelia-templating@1.0.0"
    },
    "npm:aurelia-templating-router@1.0.0": {
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.0.0",
      "aurelia-logging": "npm:aurelia-logging@1.0.0",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0",
      "aurelia-pal": "npm:aurelia-pal@1.0.0",
      "aurelia-path": "npm:aurelia-path@1.0.0",
      "aurelia-router": "npm:aurelia-router@1.0.2",
      "aurelia-templating": "npm:aurelia-templating@1.0.0"
    },
    "npm:aurelia-templating@1.0.0": {
      "aurelia-binding": "npm:aurelia-binding@1.0.1",
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.0.0",
      "aurelia-loader": "npm:aurelia-loader@1.0.0",
      "aurelia-logging": "npm:aurelia-logging@1.0.0",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0",
      "aurelia-pal": "npm:aurelia-pal@1.0.0",
      "aurelia-path": "npm:aurelia-path@1.0.0",
      "aurelia-task-queue": "npm:aurelia-task-queue@1.0.0"
    },
    "npm:babel-runtime@5.8.38": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:buffer@3.6.0": {
      "base64-js": "npm:base64-js@0.0.8",
      "child_process": "github:jspm/nodelibs-child_process@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "ieee754": "npm:ieee754@1.1.6",
      "isarray": "npm:isarray@1.0.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:core-js@0.9.18": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:inherits@2.0.1": {
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:process@0.11.6": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "vm": "github:jspm/nodelibs-vm@0.1.0"
    },
    "npm:util@0.10.3": {
      "inherits": "npm:inherits@2.0.1",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:vm-browserify@0.0.4": {
      "indexof": "npm:indexof@0.0.1"
    }
  },
  bundles: {
    "bundles/bundle.js": [
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/autocomplete/autocomplete.html!github:systemjs/plugin-text@0.0.7.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/autocomplete/autocomplete.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/barcode/barcode.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/button/button.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/buttongroup/buttongroup.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/calendar/calendar.html!github:systemjs/plugin-text@0.0.7.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/calendar/calendar.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/chart/chart.html!github:systemjs/plugin-text@0.0.7.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/chart/chart.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/chart/sparkline.html!github:systemjs/plugin-text@0.0.7.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/chart/sparkline.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/chart/stock.html!github:systemjs/plugin-text@0.0.7.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/chart/stock.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/chart/treemap.html!github:systemjs/plugin-text@0.0.7.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/chart/treemap.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/colorpalette/colorpalette.html!github:systemjs/plugin-text@0.0.7.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/colorpalette/colorpalette.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/colorpicker/colorpicker.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/combobox/combobox.html!github:systemjs/plugin-text@0.0.7.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/combobox/combobox.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/common/bindables.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/common/constants.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/common/control-properties.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/common/decorators.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/common/notify-binding-behavior.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/common/options-builder.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/common/template-compiler.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/common/template-gatherer.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/common/template.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/common/util.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/common/widget-base.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/config-builder.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/contextmenu/contextmenu.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/datepicker/datepicker.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/datetimepicker/datetimepicker.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/diagram/diagram.html!github:systemjs/plugin-text@0.0.7.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/diagram/diagram.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/draggable/draggable.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/drop-target/drop-target-area.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/drop-target/drop-target.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/dropdownlist/dropdownlist.html!github:systemjs/plugin-text@0.0.7.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/dropdownlist/dropdownlist.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/editor/editor.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/filter-menu/filter-menu.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/flatcolorpicker/flatcolorpicker.html!github:systemjs/plugin-text@0.0.7.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/flatcolorpicker/flatcolorpicker.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/gantt/gantt-col.html!github:systemjs/plugin-text@0.0.7.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/gantt/gantt-col.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/gantt/gantt.html!github:systemjs/plugin-text@0.0.7.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/gantt/gantt.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/gauges/linear-gauge.html!github:systemjs/plugin-text@0.0.7.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/gauges/linear-gauge.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/gauges/radial-gauge.html!github:systemjs/plugin-text@0.0.7.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/gauges/radial-gauge.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/grid/col.html!github:systemjs/plugin-text@0.0.7.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/grid/col.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/grid/grid-toolbar.html!github:systemjs/plugin-text@0.0.7.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/grid/grid-toolbar.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/grid/grid.html!github:systemjs/plugin-text@0.0.7.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/grid/grid.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/index.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/listview/listview.html!github:systemjs/plugin-text@0.0.7.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/listview/listview.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/map/map.html!github:systemjs/plugin-text@0.0.7.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/map/map.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/maskedtextbox/maskedtextbox.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/menu/menu.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/multiselect/multiselect.html!github:systemjs/plugin-text@0.0.7.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/multiselect/multiselect.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/notification/notification-template.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/notification/notification.html!github:systemjs/plugin-text@0.0.7.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/notification/notification.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/numerictextbox/numerictextbox.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/panelbar/panelbar.html!github:systemjs/plugin-text@0.0.7.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/panelbar/panelbar.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/pdf/pdf.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/pivotgrid/pivotconfigurator.html!github:systemjs/plugin-text@0.0.7.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/pivotgrid/pivotconfigurator.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/pivotgrid/pivotgrid.html!github:systemjs/plugin-text@0.0.7.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/pivotgrid/pivotgrid.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/popup/popup.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/progressbar/progressbar.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/qrcode/qrcode.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/rangeslider/rangeslider.html!github:systemjs/plugin-text@0.0.7.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/rangeslider/rangeslider.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/responsivepanel/responsivepanel.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/scheduler/scheduler.html!github:systemjs/plugin-text@0.0.7.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/scheduler/scheduler.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/scrollview/scrollview.html!github:systemjs/plugin-text@0.0.7.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/scrollview/scrollview.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/slider/slider.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/sortable/sortable.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/splitter/splitter.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/spreadsheet/spreadsheet.html!github:systemjs/plugin-text@0.0.7.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/spreadsheet/spreadsheet.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/switch/switch.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/tabstrip/tabstrip.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/timepicker/timepicker.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/toolbar/toolbar-item-button.html!github:systemjs/plugin-text@0.0.7.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/toolbar/toolbar-item-button.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/toolbar/toolbar-item.html!github:systemjs/plugin-text@0.0.7.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/toolbar/toolbar-item.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/toolbar/toolbar.html!github:systemjs/plugin-text@0.0.7.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/toolbar/toolbar.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/tooltip/tooltip.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/treelist/tree-col.html!github:systemjs/plugin-text@0.0.7.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/treelist/tree-col.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/treelist/treelist.html!github:systemjs/plugin-text@0.0.7.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/treelist/treelist.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/treeview/treeview.html!github:systemjs/plugin-text@0.0.7.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/treeview/treeview.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/upload/upload.html!github:systemjs/plugin-text@0.0.7.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/upload/upload.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/validator/validator.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/valueconverters/valueconverters.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/version.js",
      "github:aurelia-ui-toolkits/aurelia-kendoui-bridge@beta/window/window.js",
      "github:systemjs/plugin-json@0.1.2.js",
      "github:systemjs/plugin-json@0.1.2/json.js",
      "github:systemjs/plugin-text@0.0.7.js",
      "github:systemjs/plugin-text@0.0.7/text.js",
      "npm:aurelia-animator-css@1.0.0.js",
      "npm:aurelia-animator-css@1.0.0/aurelia-animator-css.js",
      "npm:aurelia-binding@1.0.1.js",
      "npm:aurelia-binding@1.0.1/aurelia-binding.js",
      "npm:aurelia-bootstrapper@1.0.0.js",
      "npm:aurelia-bootstrapper@1.0.0/aurelia-bootstrapper.js",
      "npm:aurelia-dependency-injection@1.0.0.js",
      "npm:aurelia-dependency-injection@1.0.0/aurelia-dependency-injection.js",
      "npm:aurelia-event-aggregator@1.0.0.js",
      "npm:aurelia-event-aggregator@1.0.0/aurelia-event-aggregator.js",
      "npm:aurelia-fetch-client@1.0.0.js",
      "npm:aurelia-fetch-client@1.0.0/aurelia-fetch-client.js",
      "npm:aurelia-framework@1.0.1.js",
      "npm:aurelia-framework@1.0.1/aurelia-framework.js",
      "npm:aurelia-history-browser@1.0.0.js",
      "npm:aurelia-history-browser@1.0.0/aurelia-history-browser.js",
      "npm:aurelia-history@1.0.0.js",
      "npm:aurelia-history@1.0.0/aurelia-history.js",
      "npm:aurelia-http-client@1.0.0.js",
      "npm:aurelia-http-client@1.0.0/aurelia-http-client.js",
      "npm:aurelia-loader-default@1.0.0.js",
      "npm:aurelia-loader-default@1.0.0/aurelia-loader-default.js",
      "npm:aurelia-loader@1.0.0.js",
      "npm:aurelia-loader@1.0.0/aurelia-loader.js",
      "npm:aurelia-logging-console@1.0.0.js",
      "npm:aurelia-logging-console@1.0.0/aurelia-logging-console.js",
      "npm:aurelia-logging@1.0.0.js",
      "npm:aurelia-logging@1.0.0/aurelia-logging.js",
      "npm:aurelia-metadata@1.0.0.js",
      "npm:aurelia-metadata@1.0.0/aurelia-metadata.js",
      "npm:aurelia-pal-browser@1.0.0.js",
      "npm:aurelia-pal-browser@1.0.0/aurelia-pal-browser.js",
      "npm:aurelia-pal@1.0.0.js",
      "npm:aurelia-pal@1.0.0/aurelia-pal.js",
      "npm:aurelia-path@1.0.0.js",
      "npm:aurelia-path@1.0.0/aurelia-path.js",
      "npm:aurelia-polyfills@1.0.0.js",
      "npm:aurelia-polyfills@1.0.0/aurelia-polyfills.js",
      "npm:aurelia-route-recognizer@1.0.0.js",
      "npm:aurelia-route-recognizer@1.0.0/aurelia-route-recognizer.js",
      "npm:aurelia-router@1.0.2.js",
      "npm:aurelia-router@1.0.2/aurelia-router.js",
      "npm:aurelia-task-queue@1.0.0.js",
      "npm:aurelia-task-queue@1.0.0/aurelia-task-queue.js",
      "npm:aurelia-templating-binding@1.0.0.js",
      "npm:aurelia-templating-binding@1.0.0/aurelia-templating-binding.js",
      "npm:aurelia-templating-resources@1.0.0.js",
      "npm:aurelia-templating-resources@1.0.0/abstract-repeater.js",
      "npm:aurelia-templating-resources@1.0.0/analyze-view-factory.js",
      "npm:aurelia-templating-resources@1.0.0/array-repeat-strategy.js",
      "npm:aurelia-templating-resources@1.0.0/aurelia-hide-style.js",
      "npm:aurelia-templating-resources@1.0.0/aurelia-templating-resources.js",
      "npm:aurelia-templating-resources@1.0.0/binding-mode-behaviors.js",
      "npm:aurelia-templating-resources@1.0.0/binding-signaler.js",
      "npm:aurelia-templating-resources@1.0.0/compose.js",
      "npm:aurelia-templating-resources@1.0.0/css-resource.js",
      "npm:aurelia-templating-resources@1.0.0/debounce-binding-behavior.js",
      "npm:aurelia-templating-resources@1.0.0/dynamic-element.js",
      "npm:aurelia-templating-resources@1.0.0/focus.js",
      "npm:aurelia-templating-resources@1.0.0/hide.js",
      "npm:aurelia-templating-resources@1.0.0/html-resource-plugin.js",
      "npm:aurelia-templating-resources@1.0.0/html-sanitizer.js",
      "npm:aurelia-templating-resources@1.0.0/if.js",
      "npm:aurelia-templating-resources@1.0.0/map-repeat-strategy.js",
      "npm:aurelia-templating-resources@1.0.0/null-repeat-strategy.js",
      "npm:aurelia-templating-resources@1.0.0/number-repeat-strategy.js",
      "npm:aurelia-templating-resources@1.0.0/repeat-strategy-locator.js",
      "npm:aurelia-templating-resources@1.0.0/repeat-utilities.js",
      "npm:aurelia-templating-resources@1.0.0/repeat.js",
      "npm:aurelia-templating-resources@1.0.0/replaceable.js",
      "npm:aurelia-templating-resources@1.0.0/sanitize-html.js",
      "npm:aurelia-templating-resources@1.0.0/set-repeat-strategy.js",
      "npm:aurelia-templating-resources@1.0.0/show.js",
      "npm:aurelia-templating-resources@1.0.0/signal-binding-behavior.js",
      "npm:aurelia-templating-resources@1.0.0/throttle-binding-behavior.js",
      "npm:aurelia-templating-resources@1.0.0/update-trigger-binding-behavior.js",
      "npm:aurelia-templating-resources@1.0.0/with.js",
      "npm:aurelia-templating-router@1.0.0.js",
      "npm:aurelia-templating-router@1.0.0/aurelia-templating-router.js",
      "npm:aurelia-templating-router@1.0.0/route-href.js",
      "npm:aurelia-templating-router@1.0.0/route-loader.js",
      "npm:aurelia-templating-router@1.0.0/router-view.js",
      "npm:aurelia-templating@1.0.0.js",
      "npm:aurelia-templating@1.0.0/aurelia-templating.js"
    ]
  }
});
